services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  avito-pvz-service:
    build:
      context: .
      args:
        SERVICE_PATH: cmd/main.go
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/root/config.yaml
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  main_data: